{
  "name": "Detalle_Forecast_de_Ventas",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "es-ES",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "Resumen Base",
        "lineageTag": "ff09f216-083b-45ed-8aff-25ba9bab257e",
        "columns": [
          {
            "name": "VERTICAL",
            "dataType": "string",
            "sourceColumn": "VERTICAL",
            "summarizeBy": "none",
            "lineageTag": "ecf8c31d-d1e1-4d55-a051-fd3f906b00e8"
          },
          {
            "name": "CLIENTE",
            "dataType": "string",
            "sourceColumn": "CLIENTE",
            "summarizeBy": "none",
            "lineageTag": "7123afb5-9584-4292-8828-797390f37fbf"
          },
          {
            "name": "PRODUCTO/PLAN",
            "dataType": "string",
            "sourceColumn": "PRODUCTO/PLAN",
            "summarizeBy": "none",
            "lineageTag": "ed548827-dc5f-4d82-a6f2-6daa9746de62"
          },
          {
            "name": "CONCEPTO 1",
            "dataType": "string",
            "sourceColumn": "CONCEPTO 1",
            "summarizeBy": "none",
            "lineageTag": "968aa5e6-5b82-4b5d-9c1f-de9e9bd28191"
          },
          {
            "name": "CONCEPTO 2",
            "dataType": "string",
            "sourceColumn": "CONCEPTO 2",
            "summarizeBy": "none",
            "lineageTag": "1b55d3a6-1073-40f9-a7d2-f690b5a03092"
          },
          {
            "name": "DIMENSIÓN",
            "dataType": "string",
            "sourceColumn": "DIMENSIÓN",
            "summarizeBy": "none",
            "lineageTag": "01ad3844-3a3c-4151-ba0f-ac1478d64088"
          },
          {
            "name": "UM",
            "dataType": "string",
            "sourceColumn": "UM",
            "summarizeBy": "none",
            "lineageTag": "a69c50ea-bce1-4ba0-9dc3-ac26806b366b"
          },
          {
            "name": "Tipo de Negocio",
            "dataType": "string",
            "sourceColumn": "Tipo de Negocio",
            "summarizeBy": "none",
            "lineageTag": "a36fb70e-d4a3-4109-85e7-44bd0ef64d29"
          },
          {
            "name": "% de ",
            "dataType": "int64",
            "sourceColumn": "% de ",
            "summarizeBy": "none",
            "lineageTag": "db2472f4-e6bb-47dd-8c96-3d4dd3ed848d"
          },
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "summarizeBy": "none",
            "lineageTag": "fd8d6ab4-557d-45cc-a1cd-15f50b0cca31"
          },
          {
            "name": "Valor",
            "dataType": "double",
            "sourceColumn": "Valor",
            "summarizeBy": "sum",
            "lineageTag": "f943bbe8-7f98-4000-b8f1-be469635e96d"
          },
          {
            "name": "TipoDato",
            "dataType": "string",
            "sourceColumn": "TipoDato",
            "summarizeBy": "none",
            "lineageTag": "35e835f9-1afa-428b-a09e-70222fa844ea"
          },
          {
            "name": "Valor en MIles",
            "dataType": "double",
            "sourceColumn": "Valor en MIles",
            "summarizeBy": "sum",
            "lineageTag": "75882d7f-d385-46a6-a01f-6d1a779209de"
          },
          {
            "name": "Cliente_Concepto2",
            "dataType": "string",
            "sourceColumn": "Cliente_Concepto2",
            "summarizeBy": "none",
            "lineageTag": "c05c7178-3640-4acc-9df9-aafd28fc0301"
          }
        ],
        "partitions": [
          {
            "name": "Resumen Base",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Origen = Excel.Workbook(File.Contents(\"\\\\ERFLS01\\Files\\Nuevos Negocios\\Juliana\\10 TRBJ\\12 Ops Comp\\05 Costos\\09 Presupuesto - Budget - Fcst\\2026\\Base de Ventas BO OC.xlsx\"), null, true),\n    Hoja = Origen{[Item=\"Resumen Base\", Kind=\"Sheet\"]}[Data],\n    QuitarRuido = Table.Skip(Hoja, 4),\n    Encabezados = Table.PromoteHeaders(QuitarRuido, [PromoteAllScalars=true]),\n    ColsTotal = List.Select(Table.ColumnNames(Encabezados), each Text.StartsWith(_, \"Total\")),\n    SinTotales = Table.RemoveColumns(Encabezados, ColsTotal),\n    SinTotalCli = Table.SelectRows(SinTotales, each Text.Trim(Text.From([CLIENTE])) <> \"Total\"),\n    SinEliminar = Table.SelectRows(SinTotalCli, each Text.Upper(Text.Trim(Text.From([#\"Tipo de Negocio\"]))) <> \"ELIMINAR\"),\n    TipoPct = Table.TransformColumnTypes(SinEliminar, {{\"% de \", Int64.Type}}),\n    Atributos = {\"SECTOR/SERVICIO CEBE/CECO\",\"CLIENTE\",\"PRODUCTO/PLAN\",\"CONCEPTO 1\",\"CONCEPTO 2\",\"DIMENSIÓN\",\"UM\",\"Tipo de Negocio\",\"% de \"},\n    Unpivot = Table.UnpivotOtherColumns(TipoPct, Atributos, \"Atributo\", \"Valor\"),\n    FechaTipo = Table.TransformColumnTypes(Unpivot, {{\"Atributo\", type date}}),\n    Fecha = Table.RenameColumns(FechaTipo, {{\"Atributo\", \"Fecha\"}}),\n    FechaMes = Table.TransformColumns(Fecha, {{\"Fecha\", Date.StartOfMonth, type date}}),\n    ValorNum = Table.TransformColumns(FechaMes, {{\"Valor\", each Number.From(_), type number}}),\n    ConTipoDato = Table.AddColumn(ValorNum, \"TipoDato\", each if [Fecha] <= Date.StartOfMonth(FechaUltimoCierre) then \"Real\" else \"Proyectado\", type text),\n    RenVertical = Table.RenameColumns(ConTipoDato, {{\"SECTOR/SERVICIO CEBE/CECO\", \"VERTICAL\"}}),\n    ConMiles = Table.AddColumn(RenVertical, \"Valor en MIles\", each [Valor] / 10000000, type number),\n    ConClave = Table.AddColumn(ConMiles, \"Cliente_Concepto2\", each Text.From([CLIENTE]) & \" | \" & Text.From([CONCEPTO 2]), type text)\nin\n    ConClave"
            }
          }
        ],
        "measures": [
          {
            "name": "Ventas",
            "expression": "SUM('Resumen Base'[Valor])",
            "lineageTag": "577382c3-51ca-46f4-b5df-2fecd564a495"
          },
          {
            "name": "Ventas Real",
            "expression": "CALCULATE([Ventas], 'Resumen Base'[TipoDato] = \"Real\")",
            "lineageTag": "c66de3f2-d7fc-4dfe-864f-a9028343e51e"
          },
          {
            "name": "Ventas Proyectado",
            "expression": "CALCULATE([Ventas], 'Resumen Base'[TipoDato] = \"Proyectado\")",
            "lineageTag": "b168dbe7-c71b-4ba0-8c70-b9d0f319c34b"
          },
          {
            "name": "Ventas Forecast",
            "expression": "[Ventas]",
            "lineageTag": "74f07c24-4472-43f9-8783-b46502e9b876"
          },
          {
            "name": "Último Cierre",
            "expression": "CALCULATE(MAX('Resumen Base'[Fecha]), 'Resumen Base'[TipoDato] = \"Real\")",
            "lineageTag": "782a71bd-f1bc-49ba-98a5-0cff21d3fc1f"
          },
          {
            "name": "Ventas Ajustada",
            "expression": "SUMX('Resumen Base', 'Resumen Base'[Valor] * (1 + COALESCE(LOOKUPVALUE('DIM_Factores'[Factores Clientes], 'DIM_Factores'[Cliente_Concepto2], 'Resumen Base'[Cliente_Concepto2]), 0)))",
            "lineageTag": "affab790-50d1-4b22-83e0-b305c7a1c6de"
          }
        ]
      },
      {
        "name": "Calendario",
        "lineageTag": "90911e7e-442f-4fe0-8db7-aacb5d94263e",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "summarizeBy": "none",
            "lineageTag": "e6a15556-d409-461e-a17a-5537be2446c3",
            "isKey": true
          },
          {
            "name": "Año",
            "dataType": "int64",
            "sourceColumn": "Año",
            "summarizeBy": "none",
            "lineageTag": "851fe1fc-9d71-4f29-95e7-15fc1d341986"
          },
          {
            "name": "Mes Nro",
            "dataType": "int64",
            "sourceColumn": "Mes Nro",
            "summarizeBy": "none",
            "lineageTag": "810a7b3e-bc2e-44ef-b8e6-e967347d8a2c"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "3632bda4-e311-4da3-a2fb-0f758324a2a4"
          },
          {
            "name": "Año-Mes",
            "dataType": "string",
            "sourceColumn": "Año-Mes",
            "summarizeBy": "none",
            "lineageTag": "d3ae846b-4fd9-43a8-816a-c5c14ebd3402"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none",
            "lineageTag": "5b2d6602-5dc0-424b-bc61-d169018b2195"
          }
        ],
        "partitions": [
          {
            "name": "Calendario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Inicio = #date(2024, 1, 1),\n    Fin = #date(2026, 12, 31),\n    N = Duration.Days(Fin - Inicio) + 1,\n    Fechas = List.Dates(Inicio, N, #duration(1, 0, 0, 0)),\n    Tabla = Table.FromList(Fechas, Splitter.SplitByNothing(), {\"Fecha\"}),\n    TFecha = Table.TransformColumnTypes(Tabla, {{\"Fecha\", type date}}),\n    Anio = Table.AddColumn(TFecha, \"Año\", each Date.Year([Fecha]), Int64.Type),\n    MesNro = Table.AddColumn(Anio, \"Mes Nro\", each Date.Month([Fecha]), Int64.Type),\n    Mes = Table.AddColumn(MesNro, \"Mes\", each Date.ToText([Fecha], [Format=\"MMMM\", Culture=\"es-ES\"]), type text),\n    AnioMes = Table.AddColumn(Mes, \"Año-Mes\", each Date.ToText([Fecha], [Format=\"yyyy-MM\", Culture=\"es-ES\"]), type text),\n    Trim = Table.AddColumn(AnioMes, \"Trimestre\", each \"Q\" & Text.From(Date.QuarterOfYear([Fecha])), type text)\nin\n    Trim"
            }
          }
        ]
      },
      {
        "name": "DIM_Cliente",
        "lineageTag": "d6c99203-23c3-4b5d-a895-82ee1b0ec16f",
        "columns": [
          {
            "name": "CLIENTE",
            "dataType": "string",
            "sourceColumn": "CLIENTE",
            "summarizeBy": "none",
            "lineageTag": "78801327-4747-4923-a703-d2813935690d"
          },
          {
            "name": "VERTICAL",
            "dataType": "string",
            "sourceColumn": "VERTICAL",
            "summarizeBy": "none",
            "lineageTag": "5d8e2a23-5b01-4446-8395-8924aed89116"
          }
        ],
        "partitions": [
          {
            "name": "DIM_Cliente",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Fuente = #\"Resumen Base\",\n    Cols = Table.SelectColumns(Fuente, {\"CLIENTE\", \"VERTICAL\"}),\n    Unicos = Table.Distinct(Cols, {\"CLIENTE\"})\nin\n    Unicos"
            }
          }
        ]
      },
      {
        "name": "DIM_Factores",
        "lineageTag": "fdfd8522-f133-48dd-a0d5-205e54947ecd",
        "columns": [
          {
            "name": "Cliente_Concepto2",
            "dataType": "string",
            "sourceColumn": "Cliente_Concepto2",
            "summarizeBy": "none",
            "lineageTag": "bc0bf54f-2f3e-4a62-b3f7-215507f32fc4"
          },
          {
            "name": "Factores Clientes",
            "dataType": "double",
            "sourceColumn": "Factores Clientes",
            "summarizeBy": "none",
            "lineageTag": "db872b53-6621-42e8-822e-bd9aec9c6050"
          }
        ],
        "partitions": [
          {
            "name": "DIM_Factores",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Origen = Excel.Workbook(File.Contents(\"O:\\Nuevos Negocios\\Juliana\\10 TRBJ\\12 Ops Comp\\05 Costos\\09 Presupuesto - Budget - Fcst\\2026\\Factores Cliente.xlsx\"), null, true),\n    Hoja = Origen{[Item=\"Factores\", Kind=\"Sheet\"]}[Data],\n    Encab = Table.PromoteHeaders(Hoja, [PromoteAllScalars=true]),\n    Tipos = Table.TransformColumnTypes(Encab, {{\"Cliente_Concepto2\", type text}, {\"Factores Clientes\", type number}}),\n    SinDup = Table.Distinct(Tipos, {\"Cliente_Concepto2\"})\nin\n    SinDup"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a1a3273b-2336-4f1d-8b31-cac680caa42c",
        "fromTable": "Resumen Base",
        "fromColumn": "Fecha",
        "toTable": "Calendario",
        "toColumn": "Fecha"
      },
      {
        "name": "de880325-ef2a-4e05-bc4e-feb9aaea83e2",
        "fromTable": "Resumen Base",
        "fromColumn": "CLIENTE",
        "toTable": "DIM_Cliente",
        "toColumn": "CLIENTE"
      },
      {
        "name": "89e7c83c-46dd-4a86-afff-f5e9d8b36fea",
        "fromTable": "Resumen Base",
        "fromColumn": "Cliente_Concepto2",
        "toTable": "DIM_Factores",
        "toColumn": "Cliente_Concepto2"
      }
    ],
    "expressions": [
      {
        "name": "FechaUltimoCierre",
        "kind": "m",
        "expression": "#date(2026, 4, 1) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "lineageTag": "8861add8-2aaa-4fec-bfa1-36b5358807d4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"FechaUltimoCierre\", \"Resumen Base\", \"DIM_Cliente\", \"DIM_Factores\", \"Calendario\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}