{
  "name": "Detalle_Forecast_de_Ventas",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "es-ES",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "Resumen Base",
        "lineageTag": "527e5aa5-2e2d-4256-bb04-54f99a96dbea",
        "columns": [
          {
            "name": "VERTICAL",
            "dataType": "string",
            "sourceColumn": "VERTICAL",
            "summarizeBy": "none",
            "lineageTag": "64b249d4-d94c-48fb-bb90-264b3c927784"
          },
          {
            "name": "CLIENTE",
            "dataType": "string",
            "sourceColumn": "CLIENTE",
            "summarizeBy": "none",
            "lineageTag": "a296789b-924c-4003-ae02-ecd1d820fbed"
          },
          {
            "name": "PRODUCTO/PLAN",
            "dataType": "string",
            "sourceColumn": "PRODUCTO/PLAN",
            "summarizeBy": "none",
            "lineageTag": "dfed89ee-446b-48bd-9813-b07b942bada6"
          },
          {
            "name": "CONCEPTO 1",
            "dataType": "string",
            "sourceColumn": "CONCEPTO 1",
            "summarizeBy": "none",
            "lineageTag": "77af91e0-44b3-4297-9379-2d6a828a39c0"
          },
          {
            "name": "CONCEPTO 2",
            "dataType": "string",
            "sourceColumn": "CONCEPTO 2",
            "summarizeBy": "none",
            "lineageTag": "330a5d34-a36c-42f8-810e-93516f3bbddc"
          },
          {
            "name": "DIMENSIÓN",
            "dataType": "string",
            "sourceColumn": "DIMENSIÓN",
            "summarizeBy": "none",
            "lineageTag": "8b5bd5fd-1b03-4a67-9917-114b4c5bcb52"
          },
          {
            "name": "UM",
            "dataType": "string",
            "sourceColumn": "UM",
            "summarizeBy": "none",
            "lineageTag": "e1c39f62-8604-4036-b616-74f0907c8337"
          },
          {
            "name": "Tipo de Negocio",
            "dataType": "string",
            "sourceColumn": "Tipo de Negocio",
            "summarizeBy": "none",
            "lineageTag": "d74e3866-3503-4cae-9949-ece1e1099c51"
          },
          {
            "name": "% de ",
            "dataType": "int64",
            "sourceColumn": "% de ",
            "summarizeBy": "none",
            "lineageTag": "5f141fb8-2107-467b-9c4b-990ddf7ac4c6"
          },
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "summarizeBy": "none",
            "lineageTag": "6464b3c4-132f-4cdb-af52-7d26b83f8a04"
          },
          {
            "name": "Valor",
            "dataType": "double",
            "sourceColumn": "Valor",
            "summarizeBy": "sum",
            "lineageTag": "1f19e050-566d-41df-b179-876193b5a7b3"
          },
          {
            "name": "TipoDato",
            "dataType": "string",
            "sourceColumn": "TipoDato",
            "summarizeBy": "none",
            "lineageTag": "b2fbd0ff-1966-4cb1-aa56-ade9c21f5345"
          },
          {
            "name": "Valor en MIles",
            "dataType": "double",
            "sourceColumn": "Valor en MIles",
            "summarizeBy": "sum",
            "lineageTag": "8a5f64ee-82f5-48c9-92d2-8acf172b00d0"
          },
          {
            "name": "Cliente_Concepto2",
            "dataType": "string",
            "sourceColumn": "Cliente_Concepto2",
            "summarizeBy": "none",
            "lineageTag": "fb180484-8e7e-4ad4-a6d4-ecc274302266"
          }
        ],
        "partitions": [
          {
            "name": "Resumen Base",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Origen = Excel.Workbook(File.Contents(\"\\\\ERFLS01\\Files\\Nuevos Negocios\\Juliana\\10 TRBJ\\12 Ops Comp\\05 Costos\\09 Presupuesto - Budget - Fcst\\2026\\Base de Ventas BO OC.xlsx\"), null, true),\n    Hoja = Origen{[Item=\"Resumen Base\", Kind=\"Sheet\"]}[Data],\n    QuitarRuido = Table.Skip(Hoja, 4),\n    Encabezados = Table.PromoteHeaders(QuitarRuido, [PromoteAllScalars=true]),\n    ColsTotal = List.Select(Table.ColumnNames(Encabezados), each Text.StartsWith(_, \"Total\")),\n    SinTotales = Table.RemoveColumns(Encabezados, ColsTotal),\n    SinTotalCli = Table.SelectRows(SinTotales, each Text.Trim(Text.From([CLIENTE])) <> \"Total\"),\n    SinEliminar = Table.SelectRows(SinTotalCli, each Text.Upper(Text.Trim(Text.From([#\"Tipo de Negocio\"]))) <> \"ELIMINAR\"),\n    TipoPct = Table.TransformColumnTypes(SinEliminar, {{\"% de \", Int64.Type}}),\n    Atributos = {\"SECTOR/SERVICIO CEBE/CECO\",\"CLIENTE\",\"PRODUCTO/PLAN\",\"CONCEPTO 1\",\"CONCEPTO 2\",\"DIMENSIÓN\",\"UM\",\"Tipo de Negocio\",\"% de \"},\n    Unpivot = Table.UnpivotOtherColumns(TipoPct, Atributos, \"Atributo\", \"Valor\"),\n    FechaTipo = Table.TransformColumnTypes(Unpivot, {{\"Atributo\", type date}}),\n    Fecha = Table.RenameColumns(FechaTipo, {{\"Atributo\", \"Fecha\"}}),\n    FechaMes = Table.TransformColumns(Fecha, {{\"Fecha\", Date.StartOfMonth, type date}}),\n    ValorNum = Table.TransformColumns(FechaMes, {{\"Valor\", each Number.From(_), type number}}),\n    ConTipoDato = Table.AddColumn(ValorNum, \"TipoDato\", each if [Fecha] <= Date.StartOfMonth(FechaUltimoCierre) then \"Real\" else \"Proyectado\", type text),\n    RenVertical = Table.RenameColumns(ConTipoDato, {{\"SECTOR/SERVICIO CEBE/CECO\", \"VERTICAL\"}}),\n    ConMiles = Table.AddColumn(RenVertical, \"Valor en MIles\", each [Valor] / 10000000, type number),\n    ConClave = Table.AddColumn(ConMiles, \"Cliente_Concepto2\", each Text.From([CLIENTE]) & \" | \" & Text.From([CONCEPTO 2]), type text)\nin\n    ConClave"
            }
          }
        ],
        "measures": [
          {
            "name": "Ventas",
            "expression": "SUM('Resumen Base'[Valor])",
            "lineageTag": "d1bdd282-3628-4a4b-a751-8da59893c4e8"
          },
          {
            "name": "Ventas Real",
            "expression": "CALCULATE([Ventas], 'Resumen Base'[TipoDato] = \"Real\")",
            "lineageTag": "84c76002-7a24-4d17-a0d8-522cd345c210"
          },
          {
            "name": "Ventas Proyectado",
            "expression": "CALCULATE([Ventas], 'Resumen Base'[TipoDato] = \"Proyectado\")",
            "lineageTag": "25995d66-c591-4823-a4b5-3cc2dd81ed92"
          },
          {
            "name": "Ventas Forecast",
            "expression": "[Ventas]",
            "lineageTag": "b688555a-a2d8-4ea5-89df-46d9fa4d2b51"
          },
          {
            "name": "Último Cierre",
            "expression": "CALCULATE(MAX('Resumen Base'[Fecha]), 'Resumen Base'[TipoDato] = \"Real\")",
            "lineageTag": "6166aa7c-adc8-4577-a206-38529685698c"
          },
          {
            "name": "Ventas Ajustada",
            "expression": "SUMX('Resumen Base', 'Resumen Base'[Valor] * (1 + COALESCE(LOOKUPVALUE('DIM_Factores'[Factores Clientes], 'DIM_Factores'[Cliente_Concepto2], 'Resumen Base'[Cliente_Concepto2]), 0)))",
            "lineageTag": "a51f9aed-487f-47df-8a6b-5e651b743bcf"
          }
        ]
      },
      {
        "name": "Calendario",
        "lineageTag": "491b1c44-81ef-40e3-8873-87cde9ee2026",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Fecha",
            "dataType": "dateTime",
            "sourceColumn": "Fecha",
            "summarizeBy": "none",
            "lineageTag": "28135732-8145-46c0-a065-f4a9b3d55834",
            "isKey": true
          },
          {
            "name": "Año",
            "dataType": "int64",
            "sourceColumn": "Año",
            "summarizeBy": "none",
            "lineageTag": "ce6beac8-27d4-49db-a1fc-cd67a21b1e57"
          },
          {
            "name": "Mes Nro",
            "dataType": "int64",
            "sourceColumn": "Mes Nro",
            "summarizeBy": "none",
            "lineageTag": "47c8d044-a988-49c6-989e-56071e6c7fa4"
          },
          {
            "name": "Mes",
            "dataType": "string",
            "sourceColumn": "Mes",
            "summarizeBy": "none",
            "lineageTag": "061750e9-90ef-4b19-914d-9eb501c039ba"
          },
          {
            "name": "Año-Mes",
            "dataType": "string",
            "sourceColumn": "Año-Mes",
            "summarizeBy": "none",
            "lineageTag": "de8dd982-e7e7-4385-8a55-484a8041f85d"
          },
          {
            "name": "Trimestre",
            "dataType": "string",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none",
            "lineageTag": "1bf094c9-a104-49dd-8dad-a885fb6ff78a"
          }
        ],
        "partitions": [
          {
            "name": "Calendario",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Inicio = #date(2024, 1, 1),\n    Fin = #date(2026, 12, 31),\n    N = Duration.Days(Fin - Inicio) + 1,\n    Fechas = List.Dates(Inicio, N, #duration(1, 0, 0, 0)),\n    Tabla = Table.FromList(Fechas, Splitter.SplitByNothing(), {\"Fecha\"}),\n    TFecha = Table.TransformColumnTypes(Tabla, {{\"Fecha\", type date}}),\n    Anio = Table.AddColumn(TFecha, \"Año\", each Date.Year([Fecha]), Int64.Type),\n    MesNro = Table.AddColumn(Anio, \"Mes Nro\", each Date.Month([Fecha]), Int64.Type),\n    Mes = Table.AddColumn(MesNro, \"Mes\", each Date.ToText([Fecha], [Format=\"MMMM\", Culture=\"es-ES\"]), type text),\n    AnioMes = Table.AddColumn(Mes, \"Año-Mes\", each Date.ToText([Fecha], [Format=\"yyyy-MM\", Culture=\"es-ES\"]), type text),\n    Trim = Table.AddColumn(AnioMes, \"Trimestre\", each \"Q\" & Text.From(Date.QuarterOfYear([Fecha])), type text)\nin\n    Trim"
            }
          }
        ]
      },
      {
        "name": "DIM_Cliente",
        "lineageTag": "d47afd4b-9acb-43cd-97ee-b2aa2da68061",
        "columns": [
          {
            "name": "CLIENTE",
            "dataType": "string",
            "sourceColumn": "CLIENTE",
            "summarizeBy": "none",
            "lineageTag": "97c40267-85d5-41ed-9cdf-a0e36e4e4365"
          },
          {
            "name": "VERTICAL",
            "dataType": "string",
            "sourceColumn": "VERTICAL",
            "summarizeBy": "none",
            "lineageTag": "a9628d8e-5cf9-4e7f-9419-7cd95275e4cc"
          }
        ],
        "partitions": [
          {
            "name": "DIM_Cliente",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Fuente = #\"Resumen Base\",\n    Cols = Table.SelectColumns(Fuente, {\"CLIENTE\", \"VERTICAL\"}),\n    Unicos = Table.Distinct(Cols, {\"CLIENTE\"})\nin\n    Unicos"
            }
          }
        ]
      },
      {
        "name": "DIM_Factores",
        "lineageTag": "d03d88a2-4003-4d99-80ca-0e3daf026666",
        "columns": [
          {
            "name": "Cliente_Concepto2",
            "dataType": "string",
            "sourceColumn": "Cliente_Concepto2",
            "summarizeBy": "none",
            "lineageTag": "1ccee7a7-7635-4618-ae08-a1cd8113f721"
          },
          {
            "name": "Factores Clientes",
            "dataType": "double",
            "sourceColumn": "Factores Clientes",
            "summarizeBy": "none",
            "lineageTag": "12c7b588-129f-4670-a42f-67af01253759"
          }
        ],
        "partitions": [
          {
            "name": "DIM_Factores",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Origen = Excel.Workbook(File.Contents(\"O:\\Nuevos Negocios\\Juliana\\10 TRBJ\\12 Ops Comp\\05 Costos\\09 Presupuesto - Budget - Fcst\\2026\\Factores Cliente.xlsx\"), null, true),\n    Hoja = Origen{[Item=\"Factores\", Kind=\"Sheet\"]}[Data],\n    Encab = Table.PromoteHeaders(Hoja, [PromoteAllScalars=true]),\n    Tipos = Table.TransformColumnTypes(Encab, {{\"Cliente_Concepto2\", type text}, {\"Factores Clientes\", type number}}),\n    SinDup = Table.Distinct(Tipos, {\"Cliente_Concepto2\"})\nin\n    SinDup"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "5487e8c6-4752-45ce-b214-f5ca9a045832",
        "fromTable": "Resumen Base",
        "fromColumn": "Fecha",
        "toTable": "Calendario",
        "toColumn": "Fecha"
      },
      {
        "name": "9b50ae6c-1e8d-4fb4-aafd-b2f49ed1d412",
        "fromTable": "Resumen Base",
        "fromColumn": "CLIENTE",
        "toTable": "DIM_Cliente",
        "toColumn": "CLIENTE"
      },
      {
        "name": "248a03e8-a437-43ac-8fda-213b71b45ef2",
        "fromTable": "Resumen Base",
        "fromColumn": "Cliente_Concepto2",
        "toTable": "DIM_Factores",
        "toColumn": "Cliente_Concepto2"
      }
    ],
    "expressions": [
      {
        "name": "FechaUltimoCierre",
        "kind": "m",
        "expression": "#date(2026, 4, 1) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "lineageTag": "27659a30-5ad8-4ffb-8855-9f805820b95d",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"FechaUltimoCierre\", \"Resumen Base\", \"DIM_Cliente\", \"DIM_Factores\", \"Calendario\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}